repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
        exclude: ^constructor-manager-ui/src/constructor_manager_ui/style/images.py
      - id: end-of-file-fixer
        exclude: ^constructor-manager-ui/src/constructor_manager_ui/style/images.py
      - id: trailing-whitespace
        exclude: ^constructor-manager-ui/src/constructor_manager_ui/style/images.py
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: [--py38-plus, --keep-runtime-typing]
        exclude: ^constructor-manager-ui/src/constructor_manager_ui/style/images.py
  - repo: https://github.com/myint/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports"]
        exclude: ^constructor-manager-ui/src/constructor_manager_ui/style/images.py
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: ^constructor-manager-ui/src/constructor_manager_ui/style/images.py
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports>=1.9.0]
        args: ["-j8", "--ignore=TYP001,E501,W503"]
        exclude: ^constructor-manager-ui/src/constructor_manager_ui/style/images.py
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.11.5
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.165
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: ^constructor-manager-ui/src/constructor_manager_ui/style/images.py
