name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'constructor-manager/**'
      - 'constructor-manager-cli/**'
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.platform }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ""
          auto-activate-base: true

      - name: Install dependencies on main environment
        run: |
          conda install -n base conda-lock mamba -y -c conda-forge

      - name: create constructor-manager-environment
        run: |
          conda create -n constructor-manager conda packaging requests pyyaml -y -c conda-forge

      - name: Install constructor-manager
        run: |
          conda activate constructor-manager
          git checkout https://github.com/goanpeca/packaging/
          cd packaging
          cd constructor-manager
          pip install -e . --no-deps

      - name: Install constructor-manager
        run: |
          conda activate constructor-manager
          cd constructor-manager-api
          pip install -e . --no-deps

      - name: Test constructor-manager-api
        run: |
          conda activate constructor-manager
          conda list
