name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'constructor-manager/**'
      - 'constructor-manager-cli/**'
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.platform }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ""
          auto-activate-base: true

      - name: Install dependencies constructor-manager-cli
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools tox tox-gh-actions
          cd constructor-manager-cli
          pip install -e .
          pip list

      - name: Test constructor-manager-cli
        run: |
          cd constructor-manager-cli
          pytest -v --color=yes --cov=constructor_manager_cli
        env:
          PLATFORM: ${{ matrix.platform }}

      - name: Install dependencies constructor-manager
        run: |
          cd constructor-manager
          pip install -e .
          pip list
        env:
          PLATFORM: ${{ matrix.platform }}

      - name: Test constructor-manager
        run: |
          cd constructor-manager
          pytest -v --color=yes --cov=constructor_manager
        env:
          PLATFORM: ${{ matrix.platform }}
