name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'constructor-manager/**'
      - 'constructor-manager-api/**'
      - 'constructor-manager-ui/**'
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.platform }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10']
    env:
        DISPLAY: ':99.0'
    steps:
      - name: Install OS dependencies
        if: contains(matrix.platform, 'ubuntu')
        run: |
          sudo apt-get update --fix-missing
          sudo apt install xvfb

      - uses: tlambert03/setup-qt-libs@v1

      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "constructor-manager"
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true
          run-post: false

      - name: Install dependencies on base environment
        run: |
          conda install -n base conda-lock mamba -c conda-forge --quiet
          conda list

      - name: create constructor-manager-environment
        run: |
          conda install -n constructor-manager conda packaging requests pyyaml -c conda-forge --quiet
          # List installed packages
          conda list

      - name: Install constructor-manager
        run: |
          # Install constructor manager
          git clone https://github.com/goanpeca/packaging.git packaging_clone
          cd packaging_clone
          git checkout constructor-updater
          cd constructor-manager
          pip install -e . --no-deps

          # Install test deps
          conda install -n constructor-manager pytest pytest-cov pytest-qt -c conda-forge --quiet

          # List installed packages
          conda list

      - name: Install constructor-manager-api
        run: |
          # Install dependencies
          conda install -n constructor-manager qtpy pyqt -c conda-forge --quiet

          # Install constructor manager
          cd packaging_clone
          git checkout constructor-cli
          cd constructor-manager-api
          pip install -e . --no-deps

          # List installed packages
          conda list

      - name: Install constructor-manager-ui
        run: |
          # Install constructor manager ui
          cd constructor-manager-ui
          pip install -e . --no-deps

          # List installed packages
          conda list

      - name: List installed packages
        run: |
          conda list

      - name: Test constructor-manager-ui (linux)
        if: contains(matrix.platform, 'ubuntu')
        run: |
          # Run Tests
          cd constructor-manager-ui/src
          xvfb-run pytest constructor_manager_ui --cov=constructor_manager_ui

      - name: Test constructor-manager-ui (other)
        if: "!contains(matrix.platform, 'ubuntu')"
        run: |
          # Run Tests
          cd constructor-manager-ui/src
          pytest constructor_manager_ui --cov=constructor_manager_ui
